### ISSUE TITLE
Typo en el Readme 

### ISSUE THREAD

**Issue by matibarriento** [ikcam/django-drf-websocket-redis#1]
En Detalles aparece la palabra aplacion en vez de aplicación

**Comment by ikcam** [comment]
Muchas gracias, de hecho este proyecto ya se encuentra depreciado tras la aparición de [channels](https://github.com/django/channels). Ejemplos de uso de channels pueden [encontrarlos aquí](https://github.com/andrewgodwin/channels-examples).
